'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';

type User = { id: string; email?: string };
type Lead = { id: string; name: string | null; push_name: string | null; phone_e164: string; temperature: string; stage: string; next_action: string | null };
type Conversation = { id: string; remote_jid: string; unread_count: number; lead: Lead };
type Message = { id: string; direction: 'inbound' | 'outbound'; text_content: string | null; status: string; created_at: string };
type Appointment = { id: string; lead_id: string; scheduled_at: string; status: string; notes: string | null; lead?: Lead };
type FollowUp = { id: string; lead_id: string; title: string; due_at: string; completed_at: string | null; lead?: Lead };
type Session = { status: string; qr_code: string | null; phone_e164: string | null };

const stages: Record<string, string> = { new: 'Novo', contacted: 'Contato feito', interested: 'Interessado', scheduled: 'Agendado', completed: 'Concluído', lost: 'Perdido' };
const temperatures: Record<string, string> = { cold: 'Frio', warm: 'Morno', hot: 'Quente' };

export default function Home() {
  const [user, setUser] = useState<User | null>(null), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(true);
  const [view, setView] = useState<'dashboard' | 'inbox' | 'leads' | 'agenda'>('dashboard'), [session, setSession] = useState<Session | null>(null), [leads, setLeads] = useState<Lead[]>([]), [conversations, setConversations] = useState<Conversation[]>([]);
  const [selected, setSelected] = useState<Conversation | null>(null), [messages, setMessages] = useState<Message[]>([]), [text, setText] = useState(''), [sending, setSending] = useState(false);
  const [appointments, setAppointments] = useState<Appointment[]>([]), [followUps, setFollowUps] = useState<FollowUp[]>([]), [search, setSearch] = useState(''), [tempFilter, setTempFilter] = useState('all'), [followLead, setFollowLead] = useState('');
  const [followTitle, setFollowTitle] = useState(''), [followDate, setFollowDate] = useState(''), [appointmentLead, setAppointmentLead] = useState(''), [appointmentDate, setAppointmentDate] = useState(''), [appointmentNotes, setAppointmentNotes] = useState('');

  useEffect(() => { void supabase.auth.getUser().then(({ data }) => { setUser(data.user ? { id: data.user.id, email: data.user.email } : null); setLoading(false); }); const { data } = supabase.auth.onAuthStateChange((_e, s) => setUser(s?.user ? { id: s.user.id, email: s.user.email } : null)); return () => data.subscription.unsubscribe(); }, []);
  useEffect(() => { if (!user) return; void loadAll(user.id); const channel = supabase.channel('crm-' + user.id).on('postgres_changes', { event: '*', schema: 'public', table: 'whatsapp_sessions', filter: 'owner_id=eq.' + user.id }, () => void loadSession(user.id)).on('postgres_changes', { event: '*', schema: 'public', table: 'leads', filter: 'owner_id=eq.' + user.id }, () => void loadLeads(user.id)).on('postgres_changes', { event: '*', schema: 'public', table: 'conversations', filter: 'owner_id=eq.' + user.id }, () => void loadConversations(user.id)).on('postgres_changes', { event: '*', schema: 'public', table: 'messages', filter: 'owner_id=eq.' + user.id }, () => { if (selected) void loadMessages(selected.id); void loadConversations(user.id); }).on('postgres_changes', { event: '*', schema: 'public', table: 'appointments', filter: 'owner_id=eq.' + user.id }, () => void loadAppointments(user.id)).on('postgres_changes', { event: '*', schema: 'public', table: 'follow_ups', filter: 'owner_id=eq.' + user.id }, () => void loadFollowUps(user.id)).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [user, selected?.id]);
  async function loadAll(id: string) { await Promise.all([loadSession(id), loadLeads(id), loadConversations(id), loadAppointments(id), loadFollowUps(id)]); }
  async function loadSession(id: string) { const { data } = await supabase.from('whatsapp_sessions').select('status,qr_code,phone_e164').eq('owner_id', id).eq('session_name', 'default').maybeSingle(); setSession(data); }
  async function loadLeads(id: string) { const { data } = await supabase.from('leads').select('id,name,push_name,phone_e164,temperature,stage,next_action').eq('owner_id', id).order('updated_at', { ascending: false }); setLeads((data ?? []) as Lead[]); }
  async function loadConversations(id: string) {
    const result = await supabase.from('conversations').select('id,remote_jid,unread_count,lead_id').eq('owner_id', id).order('last_message_at', { ascending: false, nullsFirst: false });
    if (result.error) { setError(result.error.message); return; }
    const rows = result.data ?? [];
    const leadIds = rows.map((row) => row.lead_id);
    const leadsResult = leadIds.length ? await supabase.from('leads').select('id,name,push_name,phone_e164,temperature,stage,next_action').in('id', leadIds) : { data: [], error: null };
    if (leadsResult.error) { setError(leadsResult.error.message); return; }
    const leadMap = new Map((leadsResult.data ?? []).map((lead) => [lead.id, lead]));
    setConversations(rows.map((row) => ({ ...row, lead: leadMap.get(row.lead_id) })).filter((row) => row.lead) as unknown as Conversation[]);
  }
  async function loadMessages(id: string) { const { data } = await supabase.from('messages').select('id,direction,text_content,status,created_at').eq('conversation_id', id).order('created_at'); setMessages((data ?? []) as Message[]); }
  async function loadAppointments(id: string) { const { data } = await supabase.from('appointments').select('id,lead_id,scheduled_at,status,notes,lead:leads(id,name,push_name,phone_e164)').eq('owner_id', id).order('scheduled_at'); setAppointments((data ?? []) as unknown as Appointment[]); }
  async function loadFollowUps(id: string) { const { data } = await supabase.from('follow_ups').select('id,lead_id,title,due_at,completed_at,lead:leads(id,name,push_name,phone_e164)').eq('owner_id', id).order('due_at'); setFollowUps((data ?? []) as unknown as FollowUp[]); }
  async function signIn(e: FormEvent) { e.preventDefault(); const { error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError) setError(authError.message); }
  async function sendMessage(e: FormEvent) { e.preventDefault(); if (!user || !selected || !text.trim()) return; setSending(true); const { error: sendError } = await supabase.from('outbound_messages').insert({ owner_id: user.id, conversation_id: selected.id, destination_jid: selected.remote_jid, message_type: 'text', text_content: text.trim() }); if (sendError) setError(sendError.message); else setText(''); setSending(false); }
  async function updateLead(id: string, field: string, value: string) { await supabase.from('leads').update({ [field]: value }).eq('id', id); if (user) await loadLeads(user.id); }
  async function createFollowUp(e: FormEvent) { e.preventDefault(); if (!user) return; const { error: x } = await supabase.from('follow_ups').insert({ owner_id: user.id, lead_id: followLead, title: followTitle, due_at: new Date(followDate).toISOString() }); if (x) setError(x.message); else { setFollowTitle(''); setFollowDate(''); await loadFollowUps(user.id); } }
  async function createAppointment(e: FormEvent) { e.preventDefault(); if (!user) return; const { error: x } = await supabase.from('appointments').insert({ owner_id: user.id, lead_id: appointmentLead, scheduled_at: new Date(appointmentDate).toISOString(), notes: appointmentNotes || null }); if (x) setError(x.message); else { setAppointmentLead(''); setAppointmentDate(''); setAppointmentNotes(''); await loadAppointments(user.id); } }
  async function completeFollowUp(id: string) { await supabase.from('follow_ups').update({ completed_at: new Date().toISOString() }).eq('id', id); if (user) await loadFollowUps(user.id); }
  const hot = leads.filter((l) => l.temperature === 'hot'), due = followUps.filter((f) => !f.completed_at && new Date(f.due_at) <= new Date()), filtered = leads.filter((l) => (tempFilter === 'all' || l.temperature === tempFilter) && (l.phone_e164.includes(search) || (l.name || l.push_name || '').toLowerCase().includes(search.toLowerCase())));
  const selectedName = useMemo(() => selected?.lead.name || selected?.lead.push_name || selected?.lead.phone_e164 || 'Conversa', [selected]);
  if (loading) return <main className="center"><div className="loader" /></main>;
  if (!user) return <main className="auth-shell"><section className="auth-card"><div className="brand"><span>✦</span><div><strong>Faby CRM</strong><small>Agenda & relacionamento</small></div></div><h1>Organize seus atendimentos</h1><p className="muted">Acompanhe leads e marque consultas com mais facilidade.</p><form onSubmit={signIn}><label>E-mail<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Senha<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label>{error && <p className="error">{error}</p>}<button className="primary">Entrar →</button></form></section></main>;
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>✦</span><div><strong>Faby CRM</strong><small>Agenda & relacionamento</small></div></div><div className="connection"><span className={session?.status === 'connected' ? 'dot online' : 'dot'} /><div><b>{session?.status === 'connected' ? 'WhatsApp conectado' : 'Aguardando conexão'}</b><small>{session?.phone_e164 || 'Escaneie o QR Code'}</small></div></div><nav>{[['dashboard','⌂','Visão geral'],['inbox','▣','Conversas'],['leads','♧','Leads'],['agenda','◷','Agenda']].map(([key, icon, label]) => <button key={key} className={view === key ? 'nav-active' : ''} onClick={() => setView(key as typeof view)}>{icon} <span>{label}</span></button>)}</nav><div className="profile"><div className="avatar me">{(user.email || 'U')[0].toUpperCase()}</div><div><b>{user.email}</b><small>Administrador</small></div><button onClick={() => void supabase.auth.signOut()}>↪</button></div></aside><section className="content">
    {view === 'dashboard' && <div className="page"><div className="page-heading"><div><span className="eyebrow">BOM DIA</span><h1>Visão geral</h1><p className="muted">O que precisa da sua atenção hoje.</p></div><button className="primary" onClick={() => setView('agenda')}>+ Marcar consulta</button></div><div className="stat-grid"><div className="stat"><small>Leads totais</small><strong>{leads.length}</strong><span>na sua base</span></div><div className="stat"><small>Leads quentes</small><strong className="green">{hot.length}</strong><span>maior potencial</span></div><div className="stat"><small>Follow-ups vencidos</small><strong className={due.length ? 'orange' : ''}>{due.length}</strong><span>pedem atenção</span></div><div className="stat"><small>Consultas marcadas</small><strong>{appointments.filter((a) => a.status === 'scheduled' || a.status === 'confirmed').length}</strong><span>na agenda</span></div></div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><h2>Precisa de resposta</h2><button onClick={() => setView('inbox')}>Ver todas →</button></div>{conversations.filter((c) => c.unread_count).slice(0, 5).map((c) => <button className="task-row" key={c.id} onClick={() => { setSelected(c); setView('inbox'); void loadMessages(c.id); }}><div className="avatar">{(c.lead.name || c.lead.push_name || '?')[0]}</div><div><b>{c.lead.name || c.lead.phone_e164}</b><small>{c.unread_count} mensagem(ns) nova(s)</small></div><span>→</span></button>)}{!conversations.some((c) => c.unread_count) && <p className="empty-small">Tudo respondido por enquanto.</p>}</section><section className="panel"><div className="panel-heading"><h2>Follow-ups</h2><button onClick={() => setView('leads')}>Gerenciar →</button></div>{followUps.filter((f) => !f.completed_at).slice(0, 5).map((f) => <div className="task-row" key={f.id}><div className="task-icon">✓</div><div><b>{f.title}</b><small>{f.lead?.name || f.lead?.phone_e164} · {new Date(f.due_at).toLocaleDateString('pt-BR')}</small></div><button className="check" onClick={() => void completeFollowUp(f.id)}>Concluir</button></div>)}{!followUps.some((f) => !f.completed_at) && <p className="empty-small">Nenhum follow-up pendente.</p>}</section></div></div>}
    {view === 'leads' && <div className="page"><div className="page-heading"><div><span className="eyebrow">RELACIONAMENTO</span><h1>Leads</h1><p className="muted">Classifique oportunidades e acompanhe o próximo passo.</p></div></div><div className="toolbar"><input placeholder="Buscar nome ou telefone..." value={search} onChange={(e) => setSearch(e.target.value)} /><select value={tempFilter} onChange={(e) => setTempFilter(e.target.value)}><option value="all">Todas as temperaturas</option><option value="hot">Quentes</option><option value="warm">Mornos</option><option value="cold">Frios</option></select></div><div className="panel table-panel"><table><thead><tr><th>Lead</th><th>Temperatura</th><th>Etapa</th><th>Próxima ação</th><th /></tr></thead><tbody>{filtered.map((l) => <tr key={l.id}><td><div className="lead-cell"><div className="avatar">{(l.name || l.push_name || '?')[0]}</div><div><b>{l.name || l.push_name || 'Sem nome'}</b><small>{l.phone_e164}</small></div></div></td><td><select className={'mini-select ' + l.temperature} value={l.temperature} onChange={(e) => void updateLead(l.id, 'temperature', e.target.value)}><option value="hot">Quente</option><option value="warm">Morno</option><option value="cold">Frio</option></select></td><td><select className="mini-select" value={l.stage} onChange={(e) => void updateLead(l.id, 'stage', e.target.value)}>{Object.entries(stages).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></td><td>{l.next_action || '—'}</td><td><button className="link-button" onClick={() => { setFollowLead(l.id); setView('leads'); }}>+ Follow-up</button></td></tr>)}</tbody></table>{followLead && <form className="follow-form" onSubmit={createFollowUp}><h2>Novo follow-up</h2><input value={followTitle} onChange={(e) => setFollowTitle(e.target.value)} placeholder="Ex.: Confirmar horário" required /><input type="datetime-local" value={followDate} onChange={(e) => setFollowDate(e.target.value)} required /><button className="primary">Criar lembrete</button></form>}</div></div>}
    {view === 'agenda' && <div className="page"><div className="page-heading"><div><span className="eyebrow">ATENDIMENTOS</span><h1>Agenda</h1><p className="muted">Marque e acompanhe suas consultas.</p></div></div><div className="agenda-grid"><section className="panel"><div className="panel-heading"><h2>Nova consulta</h2></div><form className="stack-form" onSubmit={createAppointment}><label>Lead<select value={appointmentLead} onChange={(e) => setAppointmentLead(e.target.value)} required><option value="">Selecione</option>{leads.map((l) => <option key={l.id} value={l.id}>{l.name || l.push_name || l.phone_e164}</option>)}</select></label><label>Data e horário<input type="datetime-local" value={appointmentDate} onChange={(e) => setAppointmentDate(e.target.value)} required /></label><label>Observação<input value={appointmentNotes} onChange={(e) => setAppointmentNotes(e.target.value)} placeholder="Ex.: primeira consulta" /></label><button className="primary">Adicionar à agenda</button></form></section><section className="panel"><div className="panel-heading"><h2>Próximas consultas</h2></div>{appointments.filter((a) => a.status !== 'cancelled').map((a) => <div className="appointment-row" key={a.id}><div className="date-box"><b>{new Date(a.scheduled_at).toLocaleDateString('pt-BR', { day: '2-digit' })}</b><small>{new Date(a.scheduled_at).toLocaleDateString('pt-BR', { month: 'short' })}</small></div><div><b>{a.lead?.name || a.lead?.push_name || a.lead?.phone_e164}</b><small>{new Date(a.scheduled_at).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })} · {a.status}</small></div></div>)}{!appointments.length && <p className="empty-small">Nenhuma consulta marcada.</p>}</section></div></div>}
    {view === 'inbox' && <div className="inbox"><aside className="inbox-list"><div className="inbox-title"><div><span className="eyebrow">ATENDIMENTO</span><h1>Conversas</h1></div><span>{conversations.length}</span></div>{conversations.map((c) => <button className={'conversation ' + (selected?.id === c.id ? 'active' : '')} key={c.id} onClick={() => { setSelected(c); void loadMessages(c.id); }}><div className="avatar">{(c.lead.name || c.lead.push_name || '?')[0]}</div><div className="conversation-copy"><strong>{c.lead.name || c.lead.push_name || c.lead.phone_e164}</strong><small>{c.lead.phone_e164}</small></div>{c.unread_count > 0 && <span className="badge">{c.unread_count}</span>}</button>)}</aside><section className="chat">{!selected ? <div className="empty"><div className="empty-icon">◌</div><h2>Selecione uma conversa</h2><p>Escolha um lead para ver o histórico.</p>{session?.status !== 'connected' && session?.qr_code && <div className="qr-card"><h3>Conecte o WhatsApp</h3><img src={session.qr_code} alt="QR Code do WhatsApp" /></div>}</div> : <><header className="chat-header"><div className="avatar large">{selectedName[0]}</div><div><h2>{selectedName}</h2><p>{selected.lead.phone_e164} · {temperatures[selected.lead.temperature]}</p></div></header><div className="messages">{messages.map((m) => <div className={'message-row ' + m.direction} key={m.id}><div className="message-bubble"><span>{m.text_content || '[Mensagem não textual]'}</span><small>{new Date(m.created_at).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })} {m.direction === 'outbound' && ' · ' + m.status}</small></div></div>)}</div><form className="composer" onSubmit={sendMessage}><input value={text} onChange={(e) => setText(e.target.value)} placeholder={session?.status === 'connected' ? 'Digite uma mensagem...' : 'WhatsApp não conectado'} disabled={sending || session?.status !== 'connected'} /><button className="primary send" disabled={sending || !text.trim() || session?.status !== 'connected'}>{sending ? '...' : 'Enviar ↑'}</button></form></>}</section></div>}
  </section></main>;
}
